USE BETSSONDB;
---------------------------------------------
TRUNCATE TABLE STG.INVOICE;
---------------------------------------------
INSERT INTO STG.INVOICE
SELECT DISTINCT I.INVOICE,
       I.QUANTITY,
	   I.PRICE,
	   COALESCE(C.SK_ID, 999999) AS COUNTRY_SK_ID,
	   COALESCE(P.SK_ID, 999999) AS PRODUCT_SK_ID,
	   COALESCE(CUS.SK_ID, 999999) AS CUSTOMER_SK_ID,
	   COALESCE(T.DATE_DT, '0001-01-01') AS INVOICEDATE,
	   CONVERT(NVARCHAR(32),HASHBYTES('MD5', CONCAT(I.INVOICE, I.QUANTITY,
	                                                I.PRICE, COALESCE(C.SK_ID, 999999),
													COALESCE(P.SK_ID, 999999), COALESCE(P.SK_ID, 999999),
													INVOICEDATE)),2) AS HASH_KEY 
FROM SRC.INVOICE I
LEFT JOIN STG.COUNTRIES C
ON I.COUNTRY = C.SRC_COUNTRY_NAME
LEFT JOIN TRG.DIMPRODUCTS P
ON I.STOCKCODE = P.STOCKCODE
LEFT JOIN TRG.DIMCUSTOMERS CUS
ON I.CUSTOMERID = CUS.CUSTOMER_ID
LEFT JOIN TRG.DIMTIME T
ON CAST(I.INVOICEDATE AS DATE) = T.DATE_DT;
